# Generated by Django 2.0.1 on 2018-01-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cad_empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[                ('cad_servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Cad_servico')),
                ('cad_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.Cad_empresa')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='cad_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.Cad_empresa'),
        ),
    ]
